/**
 * Created with JetBrains PhpStorm.
 * User: Jurii
 * Date: 22.05.13
 * Time: 2:32
 * To change this template use File | Settings | File Templates.
 */

if(window.ixedit){ixedit.deployed = true}
if(window.jQuery){jQuery(function(){
    (function(){ jQuery('a').bind('click', function(event, ui){var target = jQuery('div#clear_comment'); target.toggle('blind', { direction: 'vertical' }, 500)});})();
    (function(){ jQuery('select#dost').bind('change', function(event, ui){if(jQuery('select#dost').val() == 'Самовывоз из студии (в Одессе)'){setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.show('drop', { direction: 'down' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.hide('drop', { direction: 'up' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('input#okei'); target.removeAttr('checked')}, 0)}});})();
    (function(){ jQuery('select#aPecat').bind('change', function(event, ui){if(jQuery('div#clear_Block').is(':hidden') == true && jQuery('select#aPecat').val() != 'выбрать'){setTimeout(function(){var target = jQuery('div#clear_adress'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_email'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.show('blind', { direction: 'vertical' }, 500)}, 0)}});})();
    (function(){ jQuery('input#okei').bind('change', function(event, ui){if(jQuery('input#okei').is(':checked') == true){setTimeout(function(){var target = jQuery('input#metall_kn'); target.show('pulsate', { times: 3 }, 100)}, 0)}});})();
    (function(){ jQuery('input#okei').bind('change', function(event, ui){if(jQuery('input#okei').is(':checked') != true){setTimeout(function(){var target = jQuery('input#metall_kn'); target.hide(0)}, 0)}});})();
    (function(){ jQuery('select#opl').bind('change', function(event, ui){if(jQuery('select#opl').val() == 'пополнение баланса сайта'){setTimeout(function(){var target = jQuery('div#clear_dost'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtOpl'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('select#dost'); target.val('Самовывоз из студии (в Одессе)')}, 0)}});})();
    (function(){ jQuery('select#opl').bind('change', function(event, ui){if(jQuery('select#opl').val() == 'наложенный платеж'){setTimeout(function(){var target = jQuery('div#clear_dost'); target.show('drop', { direction: 'down' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtOpl'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_polucatel'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_us_name'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_us_surname'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_phone'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_email'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('form#formOpl'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_okei'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('select#dost'); target.val('Самовывоз из почтового отделения Вашего города')}, 0)}});})();
    (function(){ jQuery('select#dost').bind('change', function(event, ui){if(jQuery('select#dost').val() == 'Самовывоз из почтового отделения Вашего города'){setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.show('drop', { direction: 'down' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide('drop', { direction: 'up' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.hide('blind', { direction: 'horizontal' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('input#okei'); target.removeAttr('checked')}, 0); setTimeout(function(){var target = jQuery('input#metall_kn'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_email'); target.show(0)}, 0)}});})();
    (function(){ jQuery('select#dost').bind('change', function(event, ui){if(jQuery('select#dost').val() == 'Доставка до двери почтовой службой (кроме Одессы)'){setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide('drop', { direction: 'up' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.hide('blind', { direction: 'horizontal' }, 0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('input#okei'); target.removeAttr('checked')}, 0); setTimeout(function(){var target = jQuery('input#metall_kn'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_email'); target.show(0)}, 0)}});})();
    (function(){ jQuery('select#opl').bind('change', function(event, ui){if(jQuery('select#opl').val() == 'другое'){setTimeout(function(){var target = jQuery('div#clear_dost'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtOpl'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0)}});})();
    (function(){ jQuery('select#dost').bind('change', function(event, ui){if(jQuery('select#dost').val() == 'другое'){setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.show(0)}, 100); setTimeout(function(){var target = jQuery('div#clear_a'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0)}});})();
    (function(){ jQuery('textarea#txtDost').bind('click', function(event, ui){if(jQuery('div#clear_Block').is(':hidden') == true){setTimeout(function(){var target = jQuery('div#clear_Block'); target.show('blind', { direction: 'vertical' }, 500)}, 0); setTimeout(function(){var target = jQuery('div#clear_adress'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_a'); target.show(0)}, 0)}});})();
    (function(){ var target = jQuery('input#metall_kn'); target.hide(0); var target = jQuery('div#clear_txtOpl'); target.hide(0); var target = jQuery('div#clear_dost'); target.hide(0); var target = jQuery('div#clear_txtDost'); target.hide(0); var target = jQuery('div#clear_nPocta'); target.hide(0); var target = jQuery('div#clear_aPecat'); target.hide(0); var target = jQuery('div#clear_Block'); target.hide(0); var target = jQuery('div#form_bask'); target.show(0); })();
    (function(){ jQuery('select#nPocta').bind('change', function(event, ui){if(jQuery('select#nPocta').val() != 'выбрать|выбрать'){setTimeout(function(){var target = jQuery('div#clear_Block'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_adress'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('span#httpPocta'); target.show(0)}, 0)}});})();
    (function(){ jQuery('select#dost').bind('change', function(event, ui){if(jQuery('select#dost').val() == 'выбрать'){setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0)}});})();
    (function(){ jQuery('select#aPecat').bind('click', function(event, ui){if(jQuery('div#clear_Block').is(':hidden') != true){setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide('blind', { direction: 'vertical' }, 250)}, 0); setTimeout(function(){var target = jQuery('div#clear_adress'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_email'); target.hide(0)}, 0)}});})();
    (function(){ jQuery('select#nPocta').bind('change', function(event, ui){if(jQuery('div#clear_Block').is(':visible') == true && jQuery('select#nPocta').val() == 'выбрать|выбрать'){setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide('blind', { direction: 'vertical' }, 250)}, 0); setTimeout(function(){var target = jQuery('div#clear_adress'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('span#httpPocta'); target.hide(0)}, 0)}});})();
    (function(){ jQuery('select#opl').bind('change', function(event, ui){if(jQuery('select#opl').val() == 'выбрать'){setTimeout(function(){var target = jQuery('div#clear_Block'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtDost'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtOpl'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_dost'); target.hide(0)}, 0)}});})();
    (function(){ jQuery('select#dost').bind('change', function(event, ui){if(jQuery('select#dost').val() == 'Передать тренеру команды (в Одессе при полной предоплате)'){setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_adress'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtOpl'); target.addClass('')}, 0)}});})();
    (function(){ jQuery('select#dost').bind('change', function(event, ui){if(jQuery('select#dost').val() == 'Самовывоз от фотографа'){setTimeout(function(){var target = jQuery('div#clear_nPocta'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_adress'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_aPecat'); target.hide(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_Block'); target.show(0)}, 0); setTimeout(function(){var target = jQuery('div#clear_txtOpl'); target.addClass('')}, 0)}});})();
})}