#Сервер базы данных
db_server: "localhost"

#Пользователь базы данных
db_user: "okay"

#Пароль к базе
db_password: "278019"

#Имя базы
db_name: "okay"

#Префикс для таблиц
db_prefix: 's_'

#Кодировка базы данных
db_charset: 'utf8'

#Режим SQL
db_sql_mode: 'NO_ENGINE_SUBSTITUTION'

#Смещение часового пояса
db_timezone: '+04:00'
